name: store in s3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ThiagoAnunciacao/s3cmd-sync-action@v0.2.5
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_REGION: 'us-east-2'
        S3CMD_SOURCE_DIR: 'projects'
        S3CMD_EXCLUDE: '.git/*'
        S3CMD_EXCLUDE_FROM: ''
        S3CMD_DELETE_REMOVED: 'true'
        S3CMD_ADD_HEADERS: ''
        S3CMD_CF_INVALIDATE: 'true'
        S3CMD_EXTRA_OPTS: '--verbose'
